In [1]:
import numpy as np
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import time

In [2]:
driver=webdriver.Chrome()
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [ ]:
tbody=driver.find_element(By.XPATH, '/html/body/div[2]/div/div[3]/main/div[3]/div[3]/div[1]/table[2]')

In [2]:
driver=webdriver.Chrome()

In [3]:
driver.get('https://www.bcci.tv/')

In [4]:
International=driver.find_element(By.XPATH,'/html/body/header/div[3]/ul/li[1]/button')
International.click()

In [5]:
fixtures=driver.find_element(By.XPATH,'/html/body/header/div[3]/div[1]/ul/div[1]/a[2]')
fixtures.click()

In [6]:
series=[]

for i in driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]'):
    series.append(i.text)
    
series

['ENGLAND A WOMENS TOUR OF INDIA T20 SERIES',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'ENGLAND A WOMENS TOUR OF INDIA T20 SERIES',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'ENGLAND WOMEN TOUR OF INDIA 2023-24',
 'ENGLAND WOMEN TOUR OF INDIA 2023-24',
 'ENGLAND WOMEN TOUR OF INDIA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24']

In [7]:
place=[]

for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
    place.append(i.text)

place

['Mumbai',
 'Raipur',
 'Mumbai',
 'Bengaluru',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Durban',
 'Gqeberha']

In [8]:
date=[]

for i in driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]'):
    date.append(i.text)

date

['1 DECEMBER, 2023',
 '1 DECEMBER, 2023',
 '3 DECEMBER, 2023',
 '3 DECEMBER, 2023',
 '6 DECEMBER, 2023',
 '9 DECEMBER, 2023',
 '10 DECEMBER, 2023',
 '10 DECEMBER, 2023',
 '12 DECEMBER, 2023']

In [9]:
time=[]

for i in driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]'):
    time.append(i.text)
    
time

['1:30 PM IST',
 '7:00 PM IST',
 '1:30 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '9:30 PM IST',
 '9:30 PM IST']

In [10]:
Question2=pd.DataFrame({'Series':series,'place':place,'Date':date,'Time':time})

In [11]:
Question2

,Series,place,Date,Time
0,ENGLAND A WOMENS TOUR OF INDIA T20 SERIES,Mumbai,"1 DECEMBER, 2023",1:30 PM IST
1,AUSTRALIA TOUR OF INDIA 2023-24,Raipur,"1 DECEMBER, 2023",7:00 PM IST
2,ENGLAND A WOMENS TOUR OF INDIA T20 SERIES,Mumbai,"3 DECEMBER, 2023",1:30 PM IST
3,AUSTRALIA TOUR OF INDIA 2023-24,Bengaluru,"3 DECEMBER, 2023",7:00 PM IST
4,ENGLAND WOMEN TOUR OF INDIA 2023-24,Mumbai,"6 DECEMBER, 2023",7:00 PM IST
5,ENGLAND WOMEN TOUR OF INDIA 2023-24,Mumbai,"9 DECEMBER, 2023",7:00 PM IST
6,ENGLAND WOMEN TOUR OF INDIA 2023-24,Mumbai,"10 DECEMBER, 2023",7:00 PM IST
7,INDIA TOUR OF SOUTH AFRICA 2023-24,Durban,"10 DECEMBER, 2023",9:30 PM IST
8,INDIA TOUR OF SOUTH AFRICA 2023-24,Gqeberha,"12 DECEMBER, 2023",9:30 PM IST

In [12]:
driver=webdriver.Chrome()

In [13]:
driver.get('http://statisticstimes.com/')

In [18]:
economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button/i')
economy.click()

In [19]:
India=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
India.click()

In [20]:
GDP=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP.click()

In [4]:
driver=webdriver.Chrome()

In [5]:
driver.get('https:/www.billboard.com/')

In [9]:
charts=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]')
charts.click()

In [10]:
view=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
view.click()

In [11]:
song_name=[]

for i in driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3'):
    song_name.append(i.text)
    
song_name

['Lovin On Me',
 'Cruel Summer',
 'Paint The Town Red',
 'All I Want For Christmas Is You',
 'Snooze',
 'I Remember Everything',
 'Greedy',
 "Rockin' Around The Christmas Tree",
 "Is It Over Now? (Taylor's Version) [From The Vault]",
 'Water',
 'You Broke My Heart',
 'Jingle Bell Rock',
 'Last Christmas',
 'Last Night',
 "Thinkin' Bout Me",
 'A Holly Jolly Christmas',
 'First Person Shooter',
 'Fast Car',
 'Agora Hills',
 'Rich Baby Daddy',
 'Need A Favor',
 'Save Me',
 'Vampire',
 'Lil Boo Thang',
 'Fukumean',
 'Evil Ways',
 'White Horse',
 "It's The Most Wonderful Time Of The Year",
 'IDGAF',
 'Used To Be Young',
 'Dance The Night',
 'Good Good',
 'Houdini',
 'Exes',
 'Let It Snow, Let It Snow, Let It Snow!',
 'What Was I Made For?',
 'Stick Season',
 'Monaco',
 'Feliz Navidad',
 'Lose Control',
 'Dial Drunk',
 'Underneath The Tree',
 'The Christmas Song (Merry Christmas To You)',
 'My Love Mine All Mine',
 'What It Is (Block Boy)',
 'Sleigh Ride',
 'Flowers',
 'Santa Tell Me',
 'Kill Bill',
 'Virginia Beach',
 'Red Button',
 'The Shoe Fits',
 'Pretty Little Poison',
 'I Know ?',
 'World On Fire',
 "Now That We Don't Talk (Taylor's Version) [From The Vault]",
 'Harley Quinn',
 'Stories About My Brother',
 'On My Mama',
 'Wild Ones',
 "Can't Have Mine",
 '500lbs',
 "Can't Catch Me Now",
 'Strangers',
 'Great Gatsby',
 'Truck Bed',
 'Get Him Back!',
 'Try That In A Small Town',
 'Everything I Love',
 'The Painter',
 'Wick Man',
 'Qlona',
 'Standing Next To You',
 'Slime You Out',
 'Bad Idea Right?',
 "Slut! (Taylor's Version) [From The Vault]",
 'Hey Driver',
 'Segun Quien',
 'Northern Attitude',
 'Burn It Down',
 "Say Don't Go (Taylor's Version) [From The Vault]",
 'Perro Negro',
 'Que Onda',
 'Where The Wild Things Are',
 'Rich Men North Of Richmond',
 'Turks & Caicos',
 'Save Me The Trouble',
 'SkeeYee',
 'LaLa',
 'I Swear, I Really Wanted To Make A "Rap" Album But...',
 "Style (Taylor's Version)",
 'El Amor de Su Vida',
 'Too Much',
 'Meltdown',
 'Surround Sound',
 "Different 'Round Here",
 'Bongos',
 'But I Got A Beer In My Hand',
 'Calling For You',
 'Mi Ex Tenia Razon']

In [12]:
len(song_name)

100

In [13]:
driver=webdriver.Chrome()

In [14]:
driver.get('http://statisticstimes.com/')

In [15]:
economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button/i')
economy.click()

In [16]:
India=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
India.click()

In [18]:
GDP=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP.click()

In [19]:
Rank=[]

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]'):
    Rank.append(i.text)
    
Rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [20]:
State=[]

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]'):
    State.append(i.text)
    
State

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [21]:
GSDP_18_19=[]

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]'):
    GSDP_18_19.append(i.text)

GSDP_18_19

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [22]:
GSDP_19_20=[]

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]'):
    GSDP_19_20.append(i.text)
    
GSDP_19_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [23]:
Share_18_19=[]

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]'):
    Share_18_19.append(i.text)
    
Share_18_19

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [24]:
GDP=[]

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]'):
    GDP.append(i.text)
    
GDP

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [25]:
Question3=pd.DataFrame({'Rank':Rank,'State':State,'GSDP(19-20)':GSDP_19_20,'GSDP(18-19)':GSDP_18_19,'Share':Share_18_19,'GDP':GDP})

In [26]:
Question3

   Rank                      State GSDP(19-20) GSDP(18-19)   Share      GDP
0     1                Maharashtra           -   2,632,792  13.94%  399.921
1     2                 Tamil Nadu   1,845,853   1,630,208   8.63%  247.629
2     3              Uttar Pradesh   1,687,818   1,584,764   8.39%  240.726
3     4                    Gujarat           -   1,502,899   7.96%  228.290
4     5                  Karnataka   1,631,977   1,493,127   7.91%  226.806
5     6                West Bengal   1,253,832   1,089,898   5.77%  165.556
6     7                  Rajasthan   1,020,989     942,586   4.99%  143.179
7     8             Andhra Pradesh     972,782     862,957   4.57%  131.083
8     9                  Telangana     969,604     861,031   4.56%  130.791
9    10             Madhya Pradesh     906,672     809,592   4.29%  122.977
10   11                     Kerala           -     781,653   4.14%  118.733
11   12                      Delhi     856,112     774,870   4.10%  117.703
12   13                    Haryana     831,610     734,163   3.89%  111.519
13   14                      Bihar     611,804     530,363   2.81%   80.562
14   15                     Punjab     574,760     526,376   2.79%   79.957
15   16                     Odisha     521,275     487,805   2.58%   74.098
16   17                      Assam           -     315,881   1.67%   47.982
17   18               Chhattisgarh     329,180     304,063   1.61%   46.187
18   19                  Jharkhand     328,598     297,204   1.57%   45.145
19   20                Uttarakhand           -     245,895   1.30%   37.351
20   21            Jammu & Kashmir           -     155,956   0.83%   23.690
21   22           Himachal Pradesh     165,472     153,845   0.81%   23.369
22   23                        Goa      80,449      73,170   0.39%   11.115
23   24                    Tripura      55,984      49,845   0.26%    7.571
24   25                 Chandigarh           -      42,114   0.22%    6.397
25   26                 Puducherry      38,253      34,433   0.18%    5.230
26   27                  Meghalaya      36,572      33,481   0.18%    5.086
27   28                     Sikkim      32,496      28,723   0.15%    4.363
28   29                    Manipur      31,790      27,870   0.15%    4.233
29   30                   Nagaland           -      27,283   0.14%    4.144
30   31          Arunachal Pradesh           -      24,603   0.13%    3.737
31   32                    Mizoram      26,503      22,287   0.12%    3.385
32   33  Andaman & Nicobar Islands           -           -       -        -

In [27]:
driver=webdriver.Chrome()

In [28]:
driver.get(' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [29]:
Book_name=[]

for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    Book_name.append(i.text)
    
Book_name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [30]:
Author=[]

for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]'):
    Author.append(i.text)
    
Author

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [31]:
Volume_sold=[]

for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]'):
    Volume_sold.append(i.text)
    
Volume_sold

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [32]:
Publisher=[]

for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]'):
    Publisher.append(i.text)
    
Publisher

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [33]:
Genre=[]

for i in driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]'):
    Genre.append(i.text)
    
Genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [34]:
Question6=pd.DataFrame({'Book name':Book_name,'Author':Author,'Volumes sold':Volume_sold,'Publisher':Publisher,'Genre':Genre})

In [37]:
Question6

,Book name,Author,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [38]:
driver=webdriver.Chrome()

In [39]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [40]:
Name=[]

for i in driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/a'):
    Name.append(i.text)
    
Name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [41]:
year_span=[]

for i in driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/span[2]'):
    year_span.append(i.text)
    
year_span

['(2011–2019)',
 '(2016–2025)',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017–2023)',
 '(2005– )',
 '(2014–2023)',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(I) (2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016–2022)',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018–2024)',
 '(2019–2023)',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018–2024)',
 '(2006–2013)',
 '(2015–2023)',
 '(1999– )',
 '(2013–2023)',
 '(2004–2010)',
 '(2013–2022)',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016–2022)',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019–2024)',
 '(2014– )',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017–2022)',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016–2023)',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005– )',
 '(2015–2019)',
 '(2018)']

In [42]:
Genre=[]

for i in driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p/span[5]'):
    Genre.append(i.text)
    
Genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Mystery, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Sci-Fi',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Drama, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy, Romance',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [43]:
Run_time=[]

for i in driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p/span[3]'):
    Run_time.append(i.text)
    
Run_time

['4,189 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '5,702 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '3,030 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '5,280 min',
 '4,576 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '3,804 min',
 '1,455 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '5,076 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '2,109 min',
 '7,788 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '3,154 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '356 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [44]:
Ratings=[]

for i in driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/div/div[1]/span[2]'):
    Ratings.append(i.text)
    
Ratings

['9.2',
 '8.7',
 '8.1',
 '7.5',
 '7.6',
 '8',
 '6.5',
 '7.6',
 '7.5',
 '7.5',
 '8.2',
 '8.2',
 '8.7',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.5',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.7',
 '8.7',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.4',
 '8.5',
 '8.3',
 '6.2',
 '7.5',
 '8.2',
 '7.8',
 '8.5',
 '7.9',
 '8.5',
 '9.1',
 '6.5',
 '8',
 '8.7',
 '8.7',
 '7.2',
 '8.3',
 '8.5',
 '7.8',
 '7.5',
 '7.7',
 '8.7',
 '6.8',
 '8.2',
 '7.9',
 '8.3',
 '8.8',
 '8.7',
 '6.7',
 '8.3',
 '8.3',
 '7.3',
 '6.8',
 '8.4',
 '7.4',
 '8',
 '7.9',
 '6.8',
 '8.7',
 '8.4',
 '6.5',
 '7.9',
 '8.9',
 '7.8',
 '7.6',
 '9',
 '8.1',
 '8.5',
 '8.2',
 '7.3',
 '8.7',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.2',
 '8.4',
 '6.5',
 '8.2',
 '8.6',
 '9.3',
 '7.8',
 '7.5',
 '7.8',
 '8.1',
 '7',
 '8.6']

In [45]:
Votes=[]

for i in driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[4]/span[2]'):
    Votes.append(i.text)
    
Votes

['2,226,703',
 '1,293,628',
 '1,056,282',
 '310,133',
 '269,257',
 '316,005',
 '152,859',
 '332,592',
 '364,635',
 '442,615',
 '514,457',
 '848,395',
 '619,918',
 '975,269',
 '567,063',
 '175,748',
 '342,173',
 '337,582',
 '2,067,331',
 '346,911',
 '471,986',
 '567,571',
 '163,010',
 '160,122',
 '428,525',
 '233,955',
 '457,306',
 '464,858',
 '1,059,815',
 '716,229',
 '459,489',
 '409,470',
 '144,777',
 '128,319',
 '188,254',
 '160,708',
 '238,235',
 '524,308',
 '223,601',
 '467,428',
 '579,407',
 '68,794',
 '212,843',
 '523,701',
 '427,489',
 '88,539',
 '337,096',
 '270,189',
 '240,463',
 '223,825',
 '288,193',
 '751,723',
 '140,502',
 '358,073',
 '273,801',
 '582,599',
 '618,579',
 '495,297',
 '63,235',
 '115,547',
 '355,942',
 '77,889',
 '109,011',
 '252,523',
 '105,596',
 '108,904',
 '57,112',
 '153,928',
 '398,566',
 '347,386',
 '110,978',
 '267,333',
 '616,127',
 '112,251',
 '136,806',
 '617,814',
 '114,949',
 '257,464',
 '100,552',
 '24,424',
 '153,840',
 '181,844',
 '137,522',
 '40,531',
 '321,652',
 '123,725',
 '137,581',
 '78,590',
 '114,374',
 '218,191',
 '31,724',
 '196,220',
 '239,674',
 '832,613',
 '72,971',
 '53,278',
 '65,358',
 '213,175',
 '44,372',
 '278,073']

In [46]:
Question7=pd.DataFrame({'Name':Name,'year span':year_span,'Genre':Genre,'Run time':Run_time,'Ratings':Ratings,'Votes':Votes})

In [47]:
Question7

,Name,year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama","4,189 min",9.2,"2,226,703"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,293,628"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,056,282"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"310,133"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"269,257"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"53,278"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"65,358"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"213,175"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"44,372"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"278,073"

In [81]:
driver=webdriver.Chrome()

In [82]:
driver.get(' https://archive.ics.uci.edu/')

In [84]:
href=driver.find_element(By.XPATH,'//a[@class="btn-primary btn"]')
href=href.get_attribute('href')

In [85]:
driver.get(href)

In [52]:
import time

In [86]:
data=[]

for i in driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]'):
    next_button=driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
    time.sleep(2)

data

[]

In [57]:
data_urls=[]

for page in range(0,10):
    url=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for i in url:
        data_urls.append(i.get_attribute('href')) 
    next_button=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
    next_button.click()
    time.sleep(2)
    
    
data_urls

['https://archive.ics.uci.edu/dataset/53/iris',
 'https://archive.ics.uci.edu/dataset/45/heart+disease',
 'https://archive.ics.uci.edu/dataset/2/adult',
 'https://archive.ics.uci.edu/dataset/109/wine',
 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic',
 'https://archive.ics.uci.edu/dataset/34/diabetes',
 'https://archive.ics.uci.edu/dataset/602/dry+bean+dataset',
 'https://archive.ics.uci.edu/dataset/19/car+evaluation',
 'https://archive.ics.uci.edu/dataset/186/wine+quality',
 'https://archive.ics.uci.edu/dataset/222/bank+marketing',
 'https://archive.ics.uci.edu/dataset/73/mushroom',
 'https://archive.ics.uci.edu/dataset/545/rice+cammeo+and+osmancik',
 'https://archive.ics.uci.edu/dataset/1/abalone',
 'https://archive.ics.uci.edu/dataset/20/census+income',
 'https://archive.ics.uci.edu/dataset/320/student+performance',
 'https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data',
 'https://archive.ics.uci.edu/dataset/10/automobile',
 'https://archive.ics.uci.edu/dataset/14/breast+cancer',
 'https://archive.ics.uci.edu/dataset/9/auto+mpg',
 'https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original',
 'https://archive.ics.uci.edu/dataset/352/online+retail',
 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'https://archive.ics.uci.edu/dataset/94/spambase',
 'https://archive.ics.uci.edu/dataset/42/glass+identification',
 'https://archive.ics.uci.edu/dataset/102/thyroid+disease',
 'https://archive.ics.uci.edu/dataset/27/credit+approval',
 'https://archive.ics.uci.edu/dataset/80/optical+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/111/zoo',
 'https://archive.ics.uci.edu/dataset/502/online+retail+ii',
 'https://archive.ics.uci.edu/dataset/360/air+quality',
 'https://archive.ics.uci.edu/dataset/352/online+retail',
 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'https://archive.ics.uci.edu/dataset/94/spambase',
 'https://archive.ics.uci.edu/dataset/42/glass+identification',
 'https://archive.ics.uci.edu/dataset/102/thyroid+disease',
 'https://archive.ics.uci.edu/dataset/27/credit+approval',
 'https://archive.ics.uci.edu/dataset/80/optical+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/111/zoo',
 'https://archive.ics.uci.edu/dataset/502/online+retail+ii',
 'https://archive.ics.uci.edu/dataset/360/air+quality',
 'https://archive.ics.uci.edu/dataset/46/hepatitis',
 'https://archive.ics.uci.edu/dataset/468/online+shoppers+purchasing+intention+dataset',
 'https://archive.ics.uci.edu/dataset/29/computer+hardware',
 'https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption',
 'https://archive.ics.uci.edu/dataset/105/congressional+voting+records',
 'https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope',
 'https://archive.ics.uci.edu/dataset/162/forest+fires',
 'https://archive.ics.uci.edu/dataset/50/image+segmentation',
 'https://archive.ics.uci.edu/dataset/110/yeast',
 'https://archive.ics.uci.edu/dataset/151/connectionist+bench+sonar+mines+vs+rocks',
 'https://archive.ics.uci.edu/dataset/81/pen+based+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition',
 'https://archive.ics.uci.edu/dataset/101/tic+tac+toe+endgame',
 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008',
 'https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records',
 'https://archive.ics.uci.edu/dataset/76/nursery',
 'https://archive.ics.uci.edu/dataset/5/arrhythmia',
 'https://archive.ics.uci.edu/dataset/143/statlog+australian+credit+approval',
 'https://archive.ics.uci.edu/dataset/16/breast+cancer+wisconsin+prognostic',
 'https://archive.ics.uci.edu/dataset/236/seeds',
 'https://archive.ics.uci.edu/dataset/12/balance+scale',
 'https://archive.ics.uci.edu/dataset/90/soybean+large',
 'https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set',
 'https://archive.ics.uci.edu/dataset/121/eeg+database',
 'https://archive.ics.uci.edu/dataset/137/reuters+21578+text+categorization+collection',
 'https://archive.ics.uci.edu/dataset/145/statlog+heart',
 'https://archive.ics.uci.edu/dataset/33/dermatology',
 'https://archive.ics.uci.edu/dataset/146/statlog+landsat+satellite',
 'https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand',
 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified',
 'https://archive.ics.uci.edu/dataset/12/balance+scale',
 'https://archive.ics.uci.edu/dataset/90/soybean+large',
 'https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set',
 'https://archive.ics.uci.edu/dataset/121/eeg+database',
 'https://archive.ics.uci.edu/dataset/137/reuters+21578+text+categorization+collection',
 'https://archive.ics.uci.edu/dataset/145/statlog+heart',
 'https://archive.ics.uci.edu/dataset/33/dermatology',
 'https://archive.ics.uci.edu/dataset/146/statlog+landsat+satellite',
 'https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand',
 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified',
 'https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength',
 'https://archive.ics.uci.edu/dataset/91/soybean+small',
 'https://archive.ics.uci.edu/dataset/67/molecular+biology+promoter+gene+sequences',
 'https://archive.ics.uci.edu/dataset/98/statlog+project',
 'https://archive.ics.uci.edu/dataset/174/parkinsons',
 'https://archive.ics.uci.edu/dataset/601/ai4i+2020+predictive+maintenance+dataset',
 'https://archive.ics.uci.edu/dataset/107/waveform+database+generator+version+1',
 'https://archive.ics.uci.edu/dataset/332/online+news+popularity',
 'https://archive.ics.uci.edu/dataset/40/flags',
 'https://archive.ics.uci.edu/dataset/4/anonymous+microsoft+web+data',
 'https://archive.ics.uci.edu/dataset/58/lenses',
 'https://archive.ics.uci.edu/dataset/47/horse+colic',
 'https://archive.ics.uci.edu/dataset/124/cmu+face+images',
 'https://archive.ics.uci.edu/dataset/154/protein+data',
 'https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators',
 'https://archive.ics.uci.edu/dataset/70/monk+s+problems',
 'https://archive.ics.uci.edu/dataset/130/kdd+cup+1999+data',
 'https://archive.ics.uci.edu/dataset/69/molecular+biology+splice+junction+gene+sequences',
 'https://archive.ics.uci.edu/dataset/43/haberman+s+survival',
 'https://archive.ics.uci.edu/dataset/321/electricityloaddiagrams20112014']

In [71]:
data_urls

['https://archive.ics.uci.edu/dataset/53/iris',
 'https://archive.ics.uci.edu/dataset/45/heart+disease',
 'https://archive.ics.uci.edu/dataset/2/adult',
 'https://archive.ics.uci.edu/dataset/109/wine',
 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic',
 'https://archive.ics.uci.edu/dataset/34/diabetes',
 'https://archive.ics.uci.edu/dataset/602/dry+bean+dataset',
 'https://archive.ics.uci.edu/dataset/19/car+evaluation',
 'https://archive.ics.uci.edu/dataset/186/wine+quality',
 'https://archive.ics.uci.edu/dataset/222/bank+marketing',
 'https://archive.ics.uci.edu/dataset/73/mushroom',
 'https://archive.ics.uci.edu/dataset/545/rice+cammeo+and+osmancik',
 'https://archive.ics.uci.edu/dataset/1/abalone',
 'https://archive.ics.uci.edu/dataset/20/census+income',
 'https://archive.ics.uci.edu/dataset/320/student+performance',
 'https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data',
 'https://archive.ics.uci.edu/dataset/10/automobile',
 'https://archive.ics.uci.edu/dataset/14/breast+cancer',
 'https://archive.ics.uci.edu/dataset/9/auto+mpg',
 'https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original',
 'https://archive.ics.uci.edu/dataset/352/online+retail',
 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'https://archive.ics.uci.edu/dataset/94/spambase',
 'https://archive.ics.uci.edu/dataset/42/glass+identification',
 'https://archive.ics.uci.edu/dataset/102/thyroid+disease',
 'https://archive.ics.uci.edu/dataset/27/credit+approval',
 'https://archive.ics.uci.edu/dataset/80/optical+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/111/zoo',
 'https://archive.ics.uci.edu/dataset/502/online+retail+ii',
 'https://archive.ics.uci.edu/dataset/360/air+quality',
 'https://archive.ics.uci.edu/dataset/352/online+retail',
 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'https://archive.ics.uci.edu/dataset/94/spambase',
 'https://archive.ics.uci.edu/dataset/42/glass+identification',
 'https://archive.ics.uci.edu/dataset/102/thyroid+disease',
 'https://archive.ics.uci.edu/dataset/27/credit+approval',
 'https://archive.ics.uci.edu/dataset/80/optical+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/111/zoo',
 'https://archive.ics.uci.edu/dataset/502/online+retail+ii',
 'https://archive.ics.uci.edu/dataset/360/air+quality',
 'https://archive.ics.uci.edu/dataset/46/hepatitis',
 'https://archive.ics.uci.edu/dataset/468/online+shoppers+purchasing+intention+dataset',
 'https://archive.ics.uci.edu/dataset/29/computer+hardware',
 'https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption',
 'https://archive.ics.uci.edu/dataset/105/congressional+voting+records',
 'https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope',
 'https://archive.ics.uci.edu/dataset/162/forest+fires',
 'https://archive.ics.uci.edu/dataset/50/image+segmentation',
 'https://archive.ics.uci.edu/dataset/110/yeast',
 'https://archive.ics.uci.edu/dataset/151/connectionist+bench+sonar+mines+vs+rocks',
 'https://archive.ics.uci.edu/dataset/81/pen+based+recognition+of+handwritten+digits',
 'https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition',
 'https://archive.ics.uci.edu/dataset/101/tic+tac+toe+endgame',
 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008',
 'https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records',
 'https://archive.ics.uci.edu/dataset/76/nursery',
 'https://archive.ics.uci.edu/dataset/5/arrhythmia',
 'https://archive.ics.uci.edu/dataset/143/statlog+australian+credit+approval',
 'https://archive.ics.uci.edu/dataset/16/breast+cancer+wisconsin+prognostic',
 'https://archive.ics.uci.edu/dataset/236/seeds',
 'https://archive.ics.uci.edu/dataset/12/balance+scale',
 'https://archive.ics.uci.edu/dataset/90/soybean+large',
 'https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set',
 'https://archive.ics.uci.edu/dataset/121/eeg+database',
 'https://archive.ics.uci.edu/dataset/137/reuters+21578+text+categorization+collection',
 'https://archive.ics.uci.edu/dataset/145/statlog+heart',
 'https://archive.ics.uci.edu/dataset/33/dermatology',
 'https://archive.ics.uci.edu/dataset/146/statlog+landsat+satellite',
 'https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand',
 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified',
 'https://archive.ics.uci.edu/dataset/12/balance+scale',
 'https://archive.ics.uci.edu/dataset/90/soybean+large',
 'https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set',
 'https://archive.ics.uci.edu/dataset/121/eeg+database',
 'https://archive.ics.uci.edu/dataset/137/reuters+21578+text+categorization+collection',
 'https://archive.ics.uci.edu/dataset/145/statlog+heart',
 'https://archive.ics.uci.edu/dataset/33/dermatology',
 'https://archive.ics.uci.edu/dataset/146/statlog+landsat+satellite',
 'https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand',
 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified',
 'https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength',
 'https://archive.ics.uci.edu/dataset/91/soybean+small',
 'https://archive.ics.uci.edu/dataset/67/molecular+biology+promoter+gene+sequences',
 'https://archive.ics.uci.edu/dataset/98/statlog+project',
 'https://archive.ics.uci.edu/dataset/174/parkinsons',
 'https://archive.ics.uci.edu/dataset/601/ai4i+2020+predictive+maintenance+dataset',
 'https://archive.ics.uci.edu/dataset/107/waveform+database+generator+version+1',
 'https://archive.ics.uci.edu/dataset/332/online+news+popularity',
 'https://archive.ics.uci.edu/dataset/40/flags',
 'https://archive.ics.uci.edu/dataset/4/anonymous+microsoft+web+data',
 'https://archive.ics.uci.edu/dataset/58/lenses',
 'https://archive.ics.uci.edu/dataset/47/horse+colic',
 'https://archive.ics.uci.edu/dataset/124/cmu+face+images',
 'https://archive.ics.uci.edu/dataset/154/protein+data',
 'https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators',
 'https://archive.ics.uci.edu/dataset/70/monk+s+problems',
 'https://archive.ics.uci.edu/dataset/130/kdd+cup+1999+data',
 'https://archive.ics.uci.edu/dataset/69/molecular+biology+splice+junction+gene+sequences',
 'https://archive.ics.uci.edu/dataset/43/haberman+s+survival',
 'https://archive.ics.uci.edu/dataset/321/electricityloaddiagrams20112014']

In [58]:
len(data_urls)

100

In [61]:
Dataset_name=[]

for i in data_urls:
    driver.get(i)
    name=driver.find_element(By.XPATH,'//div[@class="relative flex flex w-full items-center gap-4 bg-primary p-2"]/div/div/h1')
    Dataset_name.append(name.text)
    
Dataset_name

['Iris',
 'Heart Disease',
 'Adult',
 'Wine',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Diabetes',
 'Dry Bean Dataset',
 'Car Evaluation',
 'Wine Quality',
 'Bank Marketing',
 'Mushroom',
 'Rice (Cammeo and Osmancik)',
 'Abalone',
 'Census Income',
 'Student Performance',
 'Statlog (German Credit Data)',
 'Automobile',
 'Breast Cancer',
 'Auto MPG',
 'Breast Cancer Wisconsin (Original)',
 'Online Retail',
 "Predict students' dropout and academic success",
 'Spambase',
 'Glass Identification',
 'Thyroid Disease',
 'Credit Approval',
 'Optical Recognition of Handwritten Digits',
 'Zoo',
 'Online Retail II',
 'Air Quality',
 'Online Retail',
 "Predict students' dropout and academic success",
 'Spambase',
 'Glass Identification',
 'Thyroid Disease',
 'Credit Approval',
 'Optical Recognition of Handwritten Digits',
 'Zoo',
 'Online Retail II',
 'Air Quality',
 'Hepatitis',
 'Online Shoppers Purchasing Intention Dataset',
 'Computer Hardware',
 'Individual household electric power consumption',
 'Congressional Voting Records',
 'MAGIC Gamma Telescope',
 'Forest Fires',
 'Image Segmentation',
 'Yeast',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Pen-Based Recognition of Handwritten Digits',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Tic-Tac-Toe Endgame',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Heart failure clinical records',
 'Nursery',
 'Arrhythmia',
 'Statlog (Australian Credit Approval)',
 'Breast Cancer Wisconsin (Prognostic)',
 'seeds',
 'Balance Scale',
 'Soybean (Large)',
 'Real estate valuation data set',
 'EEG Database',
 'Reuters-21578 Text Categorization Collection',
 'Statlog (Heart)',
 'Dermatology',
 'Statlog (Landsat Satellite)',
 'Seoul Bike Sharing Demand',
 'Apartment for rent classified',
 'Balance Scale',
 'Soybean (Large)',
 'Real estate valuation data set',
 'EEG Database',
 'Reuters-21578 Text Categorization Collection',
 'Statlog (Heart)',
 'Dermatology',
 'Statlog (Landsat Satellite)',
 'Seoul Bike Sharing Demand',
 'Apartment for rent classified',
 'Concrete Compressive Strength',
 'Soybean (Small)',
 'Molecular Biology (Promoter Gene Sequences)',
 'Statlog Project',
 'Parkinsons',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Waveform Database Generator (Version 1)',
 'Online News Popularity',
 'Flags',
 'Anonymous Microsoft Web Data',
 'Lenses',
 'Horse Colic',
 'CMU Face Images',
 'Protein Data',
 'CDC Diabetes Health Indicators',
 "MONK's Problems",
 'KDD Cup 1999 Data',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "Haberman's Survival",
 'ElectricityLoadDiagrams20112014']

In [62]:
len(Dataset_name)

100

In [63]:
Data_type=[]

for i in data_urls:
    driver.get(i)
    Type=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[4]/p')
    Data_type.append(Type.text)
    
Data_type

['Real',
 'Categorical, Integer, Real',
 'Categorical, Integer',
 'Integer, Real',
 'Real',
 'Categorical, Integer',
 'Integer, Real',
 'Categorical',
 'Real',
 'Categorical, Integer',
 'Categorical',
 'Real',
 'Categorical, Integer, Real',
 'Categorical, Integer',
 'Integer',
 'Categorical, Integer',
 'Categorical, Integer, Real',
 'Categorical',
 'Real, Categorical, Integer',
 'Integer',
 'Integer, Real',
 '-',
 'Integer, Real',
 'Real',
 'Categorical, Real',
 'Categorical, Integer, Real',
 'Integer',
 'Categorical, Integer',
 'Integer, Real',
 'Real',
 'Integer, Real',
 '-',
 'Integer, Real',
 'Real',
 'Categorical, Real',
 'Categorical, Integer, Real',
 'Integer',
 'Categorical, Integer',
 'Integer, Real',
 'Real',
 'Categorical, Integer, Real',
 'Integer, Real',
 'Integer',
 'Real',
 'Categorical',
 'Real',
 'Real',
 'Real',
 'Real',
 'Real',
 'Integer',
 'Integer',
 'Categorical',
 'Categorical, Integer',
 'Integer, Real',
 'Categorical',
 'Categorical, Integer, Real',
 'Categorical, Integer, Real',
 'Real',
 'Real',
 'Categorical',
 'Categorical',
 'Integer, Real',
 'Categorical, Integer, Real',
 'Categorical',
 'Categorical, Real',
 'Categorical, Integer',
 'Integer',
 'Integer, Real',
 '-',
 'Categorical',
 'Categorical',
 'Integer, Real',
 'Categorical, Integer, Real',
 'Categorical',
 'Categorical, Real',
 'Categorical, Integer',
 'Integer',
 'Integer, Real',
 '-',
 'Real',
 'Categorical',
 'Categorical',
 '-',
 'Real',
 'Real',
 'Real',
 'Integer, Real',
 'Categorical, Integer',
 'Categorical',
 'Categorical',
 'Categorical, Integer, Real',
 'Integer',
 '-',
 'Categorical, Integer',
 'Categorical',
 'Categorical, Integer',
 'Categorical',
 'Integer',
 'Real']

In [64]:
Task=[]

for i in data_urls:
    driver.get(i)
    task=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p')
    Task.append(task.text)
    
Task

['Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression',
 'Classification',
 'Classification, Regression',
 'Classification',
 'Regression',
 'Classification',
 'Regression',
 'Classification',
 'Classification, Clustering',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression, Clustering',
 'Regression',
 'Classification, Clustering',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression, Clustering',
 'Regression',
 'Classification',
 'Classification, Clustering',
 'Regression',
 'Regression, Clustering',
 'Classification',
 'Classification',
 'Regression',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression, Clustering',
 'Classification',
 'Classification, Clustering',
 'Classification, Regression, Clustering',
 'Classification',
 'Classification',
 'Classification',
 'Classification, Regression',
 'Classification, Clustering',
 'Classification',
 'Classification',
 'Regression',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Regression',
 'Classification, Regression, Clustering',
 'Classification',
 'Classification',
 'Regression',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Regression',
 'Classification, Regression, Clustering',
 'Regression',
 'Classification',
 'Classification',
 'Other',
 'Classification',
 'Classification, Regression, Causal-Discovery',
 'Classification',
 'Classification, Regression',
 'Classification',
 'Recommender-Systems',
 'Classification',
 'Classification',
 'Classification',
 '-',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Classification',
 'Regression, Clustering']

In [93]:
Instances=[]

for i in data_urls:
    driver.get(i)
    instance=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[5]/p')
    Instances.append(instance.text)

Instances

['150',
 '303',
 '48842',
 '178',
 '569',
 '1',
 '13611',
 '1728',
 '4898',
 '45211',
 '8124',
 '3810',
 '4177',
 '48842',
 '649',
 '1000',
 '205',
 '286',
 '398',
 '699',
 '541909',
 '4424',
 '4601',
 '214',
 '7200',
 '690',
 '5620',
 '101',
 '1067371',
 '9358',
 '541909',
 '4424',
 '4601',
 '214',
 '7200',
 '690',
 '5620',
 '101',
 '1067371',
 '9358',
 '155',
 '12330',
 '209',
 '2075259',
 '435',
 '19020',
 '517',
 '2310',
 '1484',
 '208',
 '10992',
 '2111',
 '958',
 '101766',
 '299',
 '12960',
 '452',
 '690',
 '198',
 '210',
 '625',
 '307',
 '414',
 '122',
 '21578',
 '270',
 '366',
 '6435',
 '8760',
 '10000',
 '625',
 '307',
 '414',
 '122',
 '21578',
 '270',
 '366',
 '6435',
 '8760',
 '10000',
 '1030',
 '47',
 '106',
 '1',
 '197',
 '10000',
 '5000',
 '39797',
 '194',
 '37711',
 '24',
 '368',
 '640',
 '-',
 '253680',
 '432',
 '4000000',
 '3190',
 '306',
 '370']

In [91]:
Year=[]

for i in data_urls:
    driver.get(i)
    try:
        year=driver.find_element(By.XPATH,'//h2[@class="text-sm text-primary-content"]')
        Year.append(year.text)
    except NoSuchElementException:
        Year.append("-")
    
    
Year

['Donated on 6/30/1988',
 'Donated on 6/30/1988',
 'Donated on 4/30/1996',
 'Donated on 6/30/1991',
 'Donated on 10/31/1995',
 '-',
 'Donated on 9/13/2020',
 'Donated on 5/31/1997',
 'Donated on 10/6/2009',
 'Donated on 2/13/2012',
 'Donated on 4/26/1987',
 'Donated on 10/5/2019',
 'Donated on 11/30/1995',
 'Donated on 4/30/1996',
 'Donated on 11/26/2014',
 'Donated on 11/16/1994',
 'Donated on 5/18/1987',
 'Donated on 7/10/1988',
 'Donated on 7/6/1993',
 'Donated on 7/14/1992',
 'Donated on 11/5/2015',
 'Donated on 12/12/2021',
 'Donated on 6/30/1999',
 'Donated on 8/31/1987',
 'Donated on 12/31/1986',
 '-',
 'Donated on 6/30/1998',
 'Donated on 5/14/1990',
 'Donated on 9/20/2019',
 'Donated on 3/22/2016',
 'Donated on 11/5/2015',
 'Donated on 12/12/2021',
 'Donated on 6/30/1999',
 'Donated on 8/31/1987',
 'Donated on 12/31/1986',
 '-',
 'Donated on 6/30/1998',
 'Donated on 5/14/1990',
 'Donated on 9/20/2019',
 'Donated on 3/22/2016',
 'Donated on 10/31/1988',
 'Donated on 8/30/2018',
 'Donated on 9/30/1987',
 'Donated on 8/29/2012',
 'Donated on 4/26/1987',
 'Donated on 4/30/2007',
 'Donated on 2/28/2008',
 'Donated on 10/31/1990',
 'Donated on 8/31/1996',
 '-',
 'Donated on 6/30/1998',
 'Donated on 8/26/2019',
 'Donated on 8/18/1991',
 'Donated on 5/2/2014',
 'Donated on 2/4/2020',
 'Donated on 5/31/1997',
 'Donated on 12/31/1997',
 '-',
 'Donated on 11/30/1995',
 'Donated on 9/28/2012',
 'Donated on 4/21/1994',
 'Donated on 7/10/1988',
 'Donated on 8/17/2018',
 'Donated on 10/12/1999',
 'Donated on 9/25/1997',
 '-',
 'Donated on 12/31/1997',
 'Donated on 2/12/1993',
 'Donated on 2/29/2020',
 'Donated on 12/25/2019',
 'Donated on 4/21/1994',
 'Donated on 7/10/1988',
 'Donated on 8/17/2018',
 'Donated on 10/12/1999',
 'Donated on 9/25/1997',
 '-',
 'Donated on 12/31/1997',
 'Donated on 2/12/1993',
 'Donated on 2/29/2020',
 'Donated on 12/25/2019',
 'Donated on 8/2/2007',
 'Donated on 12/31/1986',
 'Donated on 6/29/1990',
 'Donated on 9/30/1992',
 'Donated on 6/25/2008',
 'Donated on 8/29/2020',
 'Donated on 11/9/1988',
 'Donated on 5/30/2015',
 'Donated on 5/14/1990',
 'Donated on 10/31/1998',
 'Donated on 7/31/1990',
 'Donated on 8/5/1989',
 'Donated on 6/23/1999',
 '-',
 'Linked on 9/25/2023',
 'Donated on 9/30/1992',
 'Donated on 12/31/1998',
 'Donated on 12/31/1991',
 'Donated on 3/3/1999',
 'Donated on 3/12/2015']

In [92]:
len(Year)

100

In [90]:
from selenium.common.exceptions import NoSuchElementException

In [94]:
Question8=pd.DataFrame({'Dataset names':Dataset_name,'Data type':Data_type,'Task':Task ,'Instances':Instances ,'Year':Year })

In [95]:
Question8

,Dataset names,Data type,Task,Instances,Year
0,Iris,Real,Classification,150,Donated on 6/30/1988
1,Heart Disease,"Categorical, Integer, Real",Classification,303,Donated on 6/30/1988
2,Adult,"Categorical, Integer",Classification,48842,Donated on 4/30/1996
3,Wine,"Integer, Real",Classification,178,Donated on 6/30/1991
4,Breast Cancer Wisconsin (Diagnostic),Real,Classification,569,Donated on 10/31/1995
...,...,...,...,...,...
95,MONK's Problems,Categorical,Classification,432,Donated on 9/30/1992
96,KDD Cup 1999 Data,"Categorical, Integer",Classification,4000000,Donated on 12/31/1998
97,Molecular Biology (Splice-junction Gene Sequen...,Categorical,Classification,3190,Donated on 12/31/1991
98,Haberman's Survival,Integer,Classification,306,Donated on 3/3/1999
99,ElectricityLoadDiagrams20112014,Real,"Regression, Clustering",370,Donated on 3/12/2015